### ISSUE TITLE
Crash - MySQLShadowSyncAll

### ISSUE THREAD

**Issue by AmaVic** [perak/mysql-shadow#5]
Hello Perak !
I would like to begin with thinking you for this package that you have published, it seems very interesting !

Trying to use it, I used your code for the startup (I copyied-pasted it and replace the connection information with mine).
Doing this, the app crashes at startup and here's the log I get:

Your app is crashing. Here's the latest log.

Connected. Initializing shadow...
=> Meteor server restarted
Shadow initialized. Copying data to mongo...
Success.

C:\Users\Victor\AppData\Local\.meteor\packages\perak_mysql-shadow\1.0.8\npm\node_modules\mysql\lib\protocol\Parser.js:82
        throw err;
              ^
TypeError: Cannot read property 'message' of undefined
    at Query._callback (packages/perak:mysql-shadow/mysql-shadow.js:146:1)
    at Query.Sequence.end (C:\Users\Victor\AppData\Local\.meteor\packages\perak_mysql-shadow\1.0.8\npm\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query.ErrorPacket (C:\Users\Victor\AppData\Local\.meteor\packages\perak_mysql-shadow\1.0.8\npm\node_modules\mysql\lib\protocol\sequences\Query.js:93:8)
    at Protocol._parsePacket (C:\Users\Victor\AppData\Local\.meteor\packages\perak_mysql-shadow\1.0.8\npm\node_modules\mysql\lib\protocol\Protocol.js:270:23)
    at Parser.write (C:\Users\Victor\AppData\Local\.meteor\packages\perak_mysql-shadow\1.0.8\npm\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (C:\Users\Victor\AppData\Local\.meteor\packages\perak_mysql-shadow\1.0.8\npm\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (C:\Users\Victor\AppData\Local\.meteor\packages\perak_mysql-shadow\1.0.8\npm\node_modules\mysql\lib\Connection.js:82:28)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
Exited with code: 8
Your application is crashing. Waiting for file change.

I have seen that somebody had had the same issue and that you recommended to try adding the accounts-base package. I tryied but it didn't work for me.

I have also tried to edit a little bit the code (of meteor startup) and it turned out that when I remove the call to the MySQLShadowSyncAll function, the application starts without crashing. 

Do you have an idea of something I would have done the wrong way ?

I tryied under windows 7 64bits with meteor 1.1.0.2 and under os x yosemite (last version).

Thanks in advance and thank you again for this package !

Have a nice day.

**Comment by perak** [comment]
Hi @AmaVic

That was a bug in package. I just fixed and uploaded new version: 1.0.9

Please let me know does it work.

**Comment by perak** [comment]
P.S. you don't need "accounts-base" package

**Comment by AmaVic** [comment]
Thanks for the quick answer , @perak !
It still doesn't work, same log as before.

**Comment by perak** [comment]
Did you removed / added package again ?

**Comment by perak** [comment]
Ooops, yes, there was another bug too - fixed and uploaded: 1.0.10

**Comment by AmaVic** [comment]
Nice ! Now it works !
Thanks a lot for the quick bug resolution !
